version: "3.9"

services:
  postgres_db:
    image: postgres:11
    volumes:
      - local_postgres_db:/var/lib/postgresql/data:z
    container_name: bgl-postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    volumes:
      - .:/app
    container_name: bgl-django
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - postgres_db
      - frontend
    environment:
      - DJANGO_SETTINGS_MODULE="config.settings.dev"
    command:
      "python manage.py runserver 0.0.0.0:8000"
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: bgl-frontend
    ports:
      - "8080:8080"
    command:
      "npm run serve"

volumes:
  local_postgres_db: {}
