# Generated by Django 3.1.8 on 2021-07-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other'), (1, 'Win'), (2, 'Loss'), (3, 'Draw')]),
        ),
    ]
