# Generated by Django 3.1.8 on 2021-07-18 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20210718_1950'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ('original_game__title',)},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name_plural': 'matches'},
        ),
        migrations.RenameField(
            model_name='game',
            old_name='game',
            new_name='original_game',
        ),
    ]
