# Generated by Django 3.1.8 on 2022-03-29 22:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20210718_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='originalgame',
            options={'ordering': ('title', 'id')},
        ),
        migrations.AddField(
            model_name='game',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='match',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
        migrations.AddField(
            model_name='originalgame',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='UUID'),
        ),
    ]
